### ISSUE TITLE
Cursor instead of pagination

### ISSUE THREAD

**Issue by pkieltyka** [soundcloud/roshi#36]
I noticed Roshi uses the page/offset to get the next set of items. This doesn't work that well for real-time timelines, any thoughts to use a cursor instead?

One approach would be to take a next_id or prev_id cursor and a count. From this, you can get the index of the cursor id in an ordered redis set, and use that.

**Comment by peterbourgon** [comment]
Roshi actually supports [cursor-based pagination](http://godoc.org/github.com/soundcloud/roshi/cluster#Selecter), it's just not heavily advertised :)

**Comment by pkieltyka** [comment]
awesome! thanks
