### ISSUE TITLE
roshi-server golang app select and map order ?

### ISSUE THREAD

**Issue by lundin** [soundcloud/roshi#40]
Hi!

Thanks for roshi, i have been looking like crazy for a such a easy way of doing fan out on read. Being used in production at soundcloud makes this very cool.

I have two questions (which is probably due to my lack of go knowledge) 

1) At soundcloud, are you then using another db or redis for multiget the key responses you get back from roshi so you can create the entire feed server-side, i.e from who/tracks/metadata/likes etc or do you just supply the member server side and let client side fetch all the details on this member and the build the feed client side?

2) But why isn't the response sorted according to the timestamp/score ? I know maps are not sorted, but do i need to manually re-sort them again isnt that loosing much of the effiency from the redis set then.
```
 var items []common.KeyScoreMember
	for i := 0; i < 50000; i++ {
		timestampFloat = float64(time.Now().UnixNano())
		mycont = append(items, common.KeyScoreMember{Key: "item" + strconv.Itoa(i), Score: timestampFloat, Member: "abc" + strconv.Itoa(i*4)})
	}
	requestBody, _ := json.Marshal(mycont)

	resp, err := http.Post("http://localhost:6302/", "text/plain", bytes.NewReader(requestBody))
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

```

And then select, select.go

```
var items [][]byte
	for i := 0; i < 20; i++ {
		items = append(items, []byte("item"+strconv.Itoa(i)))
	}

	body, _ := json.Marshal(items)
	req, _ := http.NewRequest("GET", "http://localhost:6302/", bytes.NewReader(body))
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		log.Fatalf("HTTP %d", resp.StatusCode)
	}

	var normalResponse struct {
		Records map[string][]common.KeyScoreMember `json:"records"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&normalResponse); err != nil {
		log.Fatal(err)
	}

	for key := range normalResponse.Records {
		fmt.Print(key)
	}

```

Shouldnt running select.go yield the same order every time ? What am i missing ?

Many thanks!
Pontus

**Comment by peterbourgon** [comment]
> 1) At soundcloud, are you then using another db or redis for multiget the key responses you get back from roshi so you can create the entire feed server-side, i.e from who/tracks/metadata/likes etc or do you just supply the member server side and let client side fetch all the details on this member and the build the feed client side?

If the question is "how do you materialize the IDs that are returned by Roshi" the answer is "it depends". As I recall, SoundCloud does both. In some situations, there is another service in front of Roshi, which creates object representations based on the Roshi IDs. In other situations, that work is deferred to the browser, with the client JS making other requests to specific API endpoints to populate additional information.

> Shouldnt running select.go yield the same order every time ? What am i missing ?

You're creating 50k independent keys. But timestamp order is preserved only within a key. To get the behavior you want, use the same key for each insert.

**Comment by lundin** [comment]
Hi Peter, thanks for the answers. Ok i see that makes sense indeed.

And for question 2 i think i follow you and now i can see that the entries get sorted within the key correctly but i still have a question. 

> You're creating 50k independent keys. But timestamp order is preserved only within a key. To get  the behavior you want, use the same key for each insert.

So assume multiple sources/users (lets call them the keyID) creates activities which then gets inserted into the db. If i run my insert program twice and only change the member we have the same key twice, eg. item4 that has an activity with different timestamp and member.

If i then run select.go which picks 20 keys twice i get different sorted lists (but each key has correct ordered timestamp within themselves)..but to construct the overall feed i have to sort them according to some logic so i can show the very latest even in-between the keys, right ?

item11
item12
item15
item16
item19
item18
item5
item6
item8
item9
item10
item13
item2
item7
item0
item1
item14
item17
item3
item4

and

item15
item5
item18
item2
item6
item7
item1
item13
item19
item3
item9
item4
item0
item10
item11
item12
item14
item16
item17
item8

**Comment by peterbourgon** [comment]
If you select multiple keys, you will get multiple independent lists of values, in score order. If you want to merge them together into a single list, you will have to walk each list and combine them. If you use roshi-server, there is a [coalesce parameter](https://github.com/soundcloud/roshi/tree/master/roshi-server#select) which will do this for you. Does that answer the question?

**Comment by lundin** [comment]
Thanks! That made it, cool. Again thank for your time Peter!
