### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by mrzahrada** [soundcloud/roshi#47]
Hi, 
I would like to ask if this project is still active and used. Thank you

**Comment by matthiasr** [comment]
Unfortunately we do not use roshi at SoundCloud anymore. I can try to keep up with issues and PRs, but cannot make promises. All actual work will have to come from the community.

**Comment by AntyaDev** [comment]
@matthiasr 
What do you use instead of Roshi?

**Comment by discordianfish** [comment]
> [@matthiasr](https://github.com/matthiasr) What do you use instead of Roshi?

@matthiasr I second that question :)
